### ISSUE TITLE
Outline shows behind all meshes when many mesh exists

### ISSUE THREAD

**Issue by YoshieraHuang** [YoshieraHuang/bevy_outline#3]

**Comment by piaoger** [comment]
Below defect?

 
![1654251323(1)](https://user-images.githubusercontent.com/179429/171836850-6ebde4fb-a1d7-4f11-a263-77fc7a86977d.png)

**Comment by YoshieraHuang** [comment]
> Below defect?
> 
> ![1654251323(1)](https://user-images.githubusercontent.com/179429/171836850-6ebde4fb-a1d7-4f11-a263-77fc7a86977d.png)

是的。在渲染顺序上还需要再考虑考虑

**Comment by YoshieraHuang** [comment]
Fixed by lastest commits
